"""created record model and added record type to message model

Revision ID: 367f61898b8f
Revises: 7c4a4b54a0e8
Create Date: 2026-04-17 00:26:46.601146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367f61898b8f'
down_revision = '7c4a4b54a0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=5), nullable=True),
    sa.Column('parameter_field_name_1', sa.String(length=25), nullable=True),
    sa.Column('parameter_field_length_1', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_type')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_type', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('record_type')

    op.drop_table('record')
    # ### end Alembic commands ###
