"""updated records table column names

Revision ID: 927b4980245e
Revises: 367f61898b8f
Create Date: 2026-04-17 22:50:36.758786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927b4980245e'
down_revision = '367f61898b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('record')
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameter_field_name', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('parameter_field_length', sa.Integer(), nullable=True))
        batch_op.drop_column('parameter_field_length_1')
        batch_op.drop_column('parameter_field_name_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameter_field_name_1', sa.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('parameter_field_length_1', sa.INTEGER(), nullable=True))
        batch_op.drop_column('parameter_field_length')
        batch_op.drop_column('parameter_field_name')

    op.create_table('record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_type', sa.VARCHAR(length=5), nullable=True),
    sa.Column('parameter_field_name_1', sa.VARCHAR(length=25), nullable=True),
    sa.Column('parameter_field_length_1', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_type')
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=300), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('record_type', sa.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
