"""altered Record orm class and table to have composite key for record_type and field_id with generic field name, length, and added description

Revision ID: e5ed2af8b28c
Revises: 927b4980245e
Create Date: 2026-04-18 23:26:35.160761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ed2af8b28c'
down_revision = '927b4980245e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('field_name', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('field_description', sa.String(length=75), nullable=True))
        batch_op.add_column(sa.Column('field_length', sa.Integer(), nullable=True))
        batch_op.alter_column('record_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.drop_column('parameter_field_name')
        batch_op.drop_column('parameter_field_length')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('parameter_field_length', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('parameter_field_name', sa.VARCHAR(length=25), nullable=True))
        batch_op.alter_column('record_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.drop_column('field_length')
        batch_op.drop_column('field_description')
        batch_op.drop_column('field_name')
        batch_op.drop_column('field_id')

    # ### end Alembic commands ###
