"""added start and end fields to record

Revision ID: ed0ac5bb7530
Revises: e5ed2af8b28c
Create Date: 2026-04-29 23:14:02.687733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0ac5bb7530'
down_revision = 'e5ed2af8b28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field_end', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('field_end')
        batch_op.drop_column('field_start')

    # ### end Alembic commands ###
